export default class CommonConstants {
  static readonly  imageList : [string ,string][]=[
    ['fund_icon.png','工资'],
    ['insurance_icon.png','奖金'],
    ['book_icon.png','图书'],
    ['film_icon.png','电影'],
    ['housing_loan_icon.png','房租'],
    ['sport_icon.png','运动'],
    ['medical_icon.png','医疗'],
    ['baby_icon.png','兼职收入']];
 // static readonly  imageList : Array<[string ,string]>
  static readonly incomeList:Array<number>=[0,1,7];
  static readonly disbursementList:Array<number>=[0,1,2,3,4,5];
}